<?php
/*
 * Created at 21.05.2007
 *
 * @author Markus Moeller - Twick.it
 */
function utf8encode($inText) {
	if (mb_detect_encoding($inText, "UTF-8, UTF-7, ASCII, EUC-JP,SJIS, eucJP-win, SJIS-win, JIS, ISO-2022-JP, ISO-8859-1, GBK") != "UTF-8") {
		return utf8_encode($inText);
	} else {
		return $inText;
	}
}

function encodeSQL($inText) {
	$result = str_replace('\\', '\\\\' , $inText);
	$result = str_replace("'", "''", $result);
	return $result;
}


function encodeQuotes($inText) {
	return str_replace("&quot;", "&amp;quot;", $inText);
}


function removeShy($inText) {
    return str_replace(chr(194).chr(173), "", $inText);
}

/**
 * Konvertiert Unicode-Text in ASCII-Text. Dabei werden fuer diakritische
 * Zeichen entsprechende Ersatzzeichen eingesetzt.
 * @link http://www.recherche-redaktion.de/sonderzeichmap.htm Quelle
 * 
 * @param string inUnicodeText	Der Text mit Unicode-Zeichen.
 * @return string 	Der Text, bei dem diakritsche Zeichen durch ihre 
 * 					ASCII-Ersatzzeichen ersetzt worden sind. 
 */
function mapUnicodeToAscii($inUnicodeText) {
	$replace = array(
		"¢"=>"c", 
		"£"=>"Pound", 
		"¥"=>"Yen", 
		"¦"=>"|", 
		"§"=>"Paragraph", 
		"©"=>"(c)", 
		"ª"=>"a", 
		"«"=>"\"", 
		"¬"=>"not", 
		"­"=>"-", 
		"®"=>"(R)", 
		"°"=>"Grad", 
		"±"=>"Plus-Minus", 
		"²"=>"2", 
		"³"=>"3", 
		"µ"=>"Micro", 
		"·"=>" ", 
		"¸"=>" ", 
		"¹"=>"1", 
		"º"=>"o", 
		"»"=>"\"", 
		"¼"=>"1/4", 
		"½"=>"1/2", 
		"¾"=>"3/4", 
		"¿"=>"", 
		"À"=>"A", 
		"�?"=>"A", 
		"Â"=>"A", 
		"Ã"=>"A", 
		"Ä"=>"Ae", 
		"Å"=>"A", 
		"Æ"=>"AE", 
		"Ç"=>"C", 
		"È"=>"E", 
		"É"=>"E", 
		"Ê"=>"E", 
		"Ë"=>"E", 
		"Ì"=>"E", 
		"�?"=>"I", 
		"Î"=>"I", 
		"�?"=>"I", 
		"�?"=>"D", 
		"Ñ"=>"N", 
		"Ò"=>"O", 
		"Ó"=>"O", 
		"Ô"=>"O", 
		"Õ"=>"O", 
		"Ö"=>"Oe", 
		"×"=>"x", 
		"Ø"=>"O", 
		"Ù"=>"U", 
		"Ú"=>"U", 
		"Û"=>"U", 
		"Ü"=>"Ue", 
		"�?"=>"Y", 
		"Þ"=>"P", 
		"ß"=>"ss", 
		"à"=>"a", 
		"á"=>"a", 
		"â"=>"a", 
		"ã"=>"a", 
		"ä"=>"ae", 
		"å"=>"a", 
		"æ"=>"ae", 
		"ç"=>"c", 
		"è"=>"e", 
		"é"=>"e", 
		"ê"=>"e", 
		"ë"=>"e", 
		"ì"=>"i", 
		"í"=>"i", 
		"î"=>"i", 
		"ï"=>"i", 
		"ð"=>"d", 
		"ñ"=>"n", 
		"ò"=>"o", 
		"ó"=>"o", 
		"ô"=>"o", 
		"õ"=>"o", 
		"ö"=>"oe", 
		"÷"=>":", 
		"ø"=>"o", 
		"ù"=>"u", 
		"ú"=>"u", 
		"û"=>"u", 
		"ü"=>"ue", 
		"ý"=>"y", 
		"þ"=>"p", 
		"ÿ"=>"y", 
		"Ā"=>"A", 
		"�?"=>"a", 
		"Ă"=>"A", 
		"ă"=>"a", 
		"Ą"=>"A", 
		"ą"=>"a", 
		"Ć"=>"C", 
		"ć"=>"c", 
		"Ĉ"=>"C", 
		"ĉ"=>"c", 
		"Ċ"=>"C", 
		"ċ"=>"c", 
		"Č"=>"C", 
		"�?"=>"c", 
		"Ď"=>"D", 
		"�?"=>"d", 
		"�?"=>"D", 
		"đ"=>"d", 
		"Ē"=>"E", 
		"ē"=>"e", 
		"Ĕ"=>"E", 
		"ĕ"=>"e", 
		"Ė"=>"E", 
		"ė"=>"e", 
		"Ę"=>"E", 
		"ę"=>"e", 
		"Ě"=>"E", 
		"ě"=>"e", 
		"Ĝ"=>"G", 
		"�?"=>"g", 
		"Ğ"=>"G", 
		"ğ"=>"g", 
		"Ġ"=>"G", 
		"ġ"=>"g", 
		"Ģ"=>"G", 
		"ģ"=>"g", 
		"Ĥ"=>"H", 
		"ĥ"=>"h", 
		"Ħ"=>"H", 
		"ħ"=>"h", 
		"Ĩ"=>"I", 
		"ĩ"=>"i", 
		"Ī"=>"I", 
		"ī"=>"i", 
		"Ĭ"=>"I", 
		"ĭ"=>"i", 
		"Į"=>"I", 
		"į"=>"i", 
		"İ"=>"I", 
		"ı"=>"i", 
		"Ĳ"=>"IJ", 
		"ĳ"=>"ij", 
		"Ĵ"=>"J", 
		"ĵ"=>"j", 
		"Ķ"=>"K", 
		"ķ"=>"k", 
		"ĸ"=>"k", 
		"Ĺ"=>"L", 
		"ĺ"=>"l", 
		"Ļ"=>"L", 
		"ļ"=>"l", 
		"Ľ"=>"L", 
		"ľ"=>"l", 
		"Ŀ"=>"L", 
		"ŀ"=>"l", 
		"�?"=>"L", 
		"ł"=>"l", 
		"Ń"=>"N", 
		"ń"=>"n", 
		"Ņ"=>"N", 
		"ņ"=>"n", 
		"Ň"=>"N", 
		"ŉ"=>"n", 
		"ŉ"=>"'n", 
		"Ŋ"=>"N", 
		"ŋ"=>"n", 
		"Ō"=>"O", 
		"�?"=>"o", 
		"Ŏ"=>"O", 
		"�?"=>"o", 
		"�?"=>"O", 
		"ő"=>"o", 
		"Œ"=>"OE", 
		"œ"=>"oe", 
		"Ŕ"=>"R", 
		"ŕ"=>"r", 
		"Ŗ"=>"R", 
		"ŗ"=>"r", 
		"ŗ"=>"R", 
		"ř"=>"r", 
		"Ś"=>"S", 
		"ś"=>"s", 
		"Ŝ"=>"S", 
		"�?"=>"s", 
		"Ş"=>"S", 
		"ş"=>"s", 
		"Š"=>"S", 
		"š"=>"s", 
		"Ţ"=>"T", 
		"ţ"=>"t", 
		"Ť"=>"T", 
		"ť"=>"t", 
		"Ŧ"=>"T", 
		"ŧ"=>"t", 
		"Ũ"=>"U", 
		"ũ"=>"u", 
		"Ū"=>"U", 
		"ū"=>"u", 
		"Ŭ"=>"U", 
		"ŭ"=>"u", 
		"Ů"=>"U", 
		"ů"=>"u", 
		"Ű"=>"U", 
		"ű"=>"u", 
		"Ų"=>"U", 
		"ų"=>"u", 
		"Ŵ"=>"W", 
		"ŵ"=>"w", 
		"Ŷ"=>"Y", 
		"ŷ"=>"y", 
		"Ÿ"=>"Y", 
		"Ź"=>"Z", 
		"ź"=>"z", 
		"Ż"=>"Z", 
		"ż"=>"z", 
		"Ž"=>"Z", 
		"ž"=>"z", 
		"ſ"=>"s", 
		"Ȁ"=>"A", 
		"�?"=>"a", 
		"Ȃ"=>"A", 
		"ȃ"=>"a", 
		"Ȅ"=>"E", 
		"ȅ"=>"e", 
		"Ȇ"=>"E", 
		"ȇ"=>"e", 
		"Ȉ"=>"I", 
		"ȉ"=>"i", 
		"Ȋ"=>"I", 
		"ȋ"=>"i", 
		"Ȍ"=>"O", 
		"�?"=>"o", 
		"Ȏ"=>"O", 
		"�?"=>"o", 
		"�?"=>"R", 
		"ȑ"=>"r", 
		"Ȓ"=>"R", 
		"ȓ"=>"r", 
		"Ȕ"=>"U", 
		"ȕ"=>"u", 
		"Ȗ"=>"U", 
		"ȗ"=>"u", 
		"�?"=>"-", 
		"‑"=>"-", 
		"‒"=>"-", 
		"–"=>"-", 
		"—"=>"-", 
		"―"=>"-", 
		"‘"=>"'", 
		"’"=>"'", 
		"‚"=>"'", 
		"‛"=>"'", 
		"“"=>"\"", 
		"�?"=>"\"", 
		"„"=>"\"", 
		"‟"=>"\"", 
		"†"=>"+", 
		"‡"=>"+", 
		"•"=>"-", 
		"?"=>"-", 
		"…"=>"...", 
		"‹"=>"'", 
		"›"=>"'"
	);
	
	return strtr($inUnicodeText, $replace);
}


function myhtmlentities($inText) {
	$result = htmlentities($inText, ENT_QUOTES, "ISO-8859-1");
	if (!$result) {
		$result = htmlentities($inText, ENT_QUOTES, "utf-8");
	} 
	if (!$result) {
		$result = $inText;
	}
	
	return $result;
}
?>